return {
  require 'custom.plugins.snacks',
  require 'custom.plugins.basics',
  require 'custom.plugins.catppucchin',
  --require 'custom.plugins.alpha',
  require 'custom.plugins.smear',
  require 'custom.plugins.cmdline',
  require 'custom.plugins.image_support',
  require 'custom.plugins.notebook',
  require 'custom.plugins.undotree',
  require 'custom.plugins.arduino',
  require 'custom.plugins.nvim-lsp',
  require 'custom.plugins.git',
  require 'custom.plugins.lualine',
  require 'custom.plugins.cmp',
  require 'custom.plugins.neorg',
  require 'custom.plugins.persistance',
}
